# Generated by Django 4.2.2 on 2023-06-16 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None),
        ),
    ]
