# Generated by Django 4.2.2 on 2023-06-16 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE weather_info_summary ALTER COLUMN data TYPE jsonb[] USING array[data]',
            'ALTER TABLE weather_info_summary ALTER COLUMN data TYPE jsonb[] USING data::jsonb[]',
        ),
    ]
