# Generated by Django 4.2.2 on 2023-06-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info', '0002_alter_summary_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='order',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='parameter',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='region',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
