# Generated by Django 4.2.2 on 2023-06-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info', '0003_alter_summary_order_alter_summary_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='order',
            field=models.CharField(choices=[('ranked', 'ranked'), ('date', 'date')], max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='parameter',
            field=models.CharField(choices=[('Tmax', 'Tmax'), ('Tmin', 'Tmin'), ('Tmean', 'Tmean'), ('Sunshine', 'Sunshine'), ('Rainfall', 'Rainfall'), ('Raindays1mm', 'Raindays1mm'), ('AirFrost', 'AirFrost')], max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='region',
            field=models.CharField(choices=[('UK', 'UK'), ('England', 'England'), ('Wales', 'Wales'), ('Scotland', 'Scotland'), ('Northern_Ireland', 'Northern_Ireland'), ('England_and_Wales', 'England_and_Wales'), ('England_N', 'England_N'), ('England_S', 'England_S'), ('Scotland_N', 'Scotland_N'), ('Scotland_E', 'Scotland_E'), ('Scotland_W', 'Scotland_W'), ('England_E_and_NE', 'England_E_and_NE'), ('England_NW_and_N_Wales', 'England_NW_and_N_Wales'), ('Midlands', 'Midlands'), ('East_Anglia', 'East_Anglia'), ('England_SW_and_S_Wales', 'England_SW_and_S_Wales'), ('England_SE_and_Central_S', 'England_SE_and_Central_S')], max_length=100),
        ),
    ]
