# Generated by Django 4.2.2 on 2023-06-19 01:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info', '0004_alter_summary_order_alter_summary_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='summary',
            name='order',
            field=models.CharField(choices=[('rank-order', 'rank-order'), ('year-order', 'year-order')], max_length=100),
        ),
    ]
